name: egsfree
description: A cli to fetch EpicGamesStore free games.
version: 1.0.2
homepage: https://github.com/zkayia/egsfree
issue_tracker: https://github.com/zkayia/egsfree/issues
repository: https://github.com/zkayia/egsfree

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  args: ^2.3.0
  dolumns: ^2.0.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
