name: egsfree
description: A cli to fetch EpicGamesStore free games.
version: 1.2.2
homepage: https://github.com/zkayia/egsfree
issue_tracker: https://github.com/zkayia/egsfree/issues
repository: https://github.com/zkayia/egsfree

publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  args: ^2.3.0
  binary_updater:
    git: https://github.com/zkayia/binary_updater
  collection: ^1.16.0
  dolumns: ^2.0.0
  version: ^3.0.2

dev_dependencies:
  lints: ^2.0.0
