name: egs_free_games
description: A sample command-line application.
version: 1.0.0
homepage: https://github.com/zkayia/egs-free-games
issue_tracker: https://github.com/zkayia/egs-free-games/issues
repository: https://github.com/zkayia/egs-free-games

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  args: ^2.3.0
  dolumns: ^2.0.0
  http: ^0.13.4

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
